Numpy Primer
============

In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [3]:
np.zeros((2, 4, 3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [4]:
np.ones((2, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [6]:
np.ones((2, 4)) * 3

array([[ 3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.]])

In [7]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
np.random.randn(3, 4) # normal distributed values

array([[-0.35139805, -0.06687083,  1.15269961, -0.20571833],
       [-1.44890359,  0.51328624, -1.16084358,  0.16854509],
       [-1.26222229,  1.55406748, -0.01622312, -0.45176877]])

In [10]:
list(range(4))

[0, 1, 2, 3]

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [16]:
a = np.array([[1.0, 2.0], [5.0, 4.0]])
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [17]:
b = np.array([[4, 3], [2, 1]])
b

array([[4, 3],
       [2, 1]])

In [18]:
print(b.dtype, a.dtype) # each array has a data type (casting rules apply for int -> float)

(dtype('int64'), dtype('float64'))


In [19]:
v = np.array([0.5, 2.0])
v

array([ 0.5,  2. ])

In [20]:
np.array(["Mickey", "Mouse"]) # can hold more than just numbers

array(['Mickey', 'Mouse'], 
      dtype='|S6')

In [21]:
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [22]:
a.diagonal()

array([ 1.,  4.])

In [23]:
np.transpose(a) 

array([[ 1.,  5.],
       [ 2.,  4.]])

In [24]:
a.T # shorthand

array([[ 1.,  5.],
       [ 2.,  4.]])

In [26]:
a.diagonal(1) # first diagonal

array([ 2.])

In [27]:
a.shape # returns a regular python tuple

(2, 2)

In [29]:
a.shape[0]

2

In [30]:
v.shape

(2,)

In [32]:
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [34]:
a[:, 0]

array([ 1.,  5.])

In [31]:
np.sum(a), np.sum(a, axis=0), np.sum(a, axis=1) # reduce-operations reduce the whole array if no axis is specified

(12.0, array([ 6.,  6.]), array([ 3.,  9.]))

In [35]:
np.max(a, axis=1), np.mean(a, axis=0)

(array([ 2.,  5.]), array([ 3.,  3.]))

In [36]:
np.linalg.inv(a) 

array([[-0.66666667,  0.33333333],
       [ 0.83333333, -0.16666667]])

In [37]:
np.dot(a, b) # matrix multiplication

array([[  8.,   5.],
       [ 28.,  19.]])

In [38]:
a.dot(b) #shorthand : expects m x n matrix with a n x p matrix

array([[  8.,   5.],
       [ 28.,  19.]])

In [40]:
a.dot(np.linalg.inv(a)) # should be the identity matrix

array([[  1.00000000e+00,   0.00000000e+00],
       [ -4.44089210e-16,   1.00000000e+00]])

In [42]:
print(a)
print(b)

[[ 1.  2.]
 [ 5.  4.]]
[[4 3]
 [2 1]]


In [41]:
a * b # math operations are element-wise

array([[  4.,   6.],
       [ 10.,   4.]])

In [43]:
a - b

array([[-3., -1.],
       [ 3.,  3.]])

In [44]:
np.linalg.solve(a, v) # solves ax = v

array([ 0.33333333,  0.08333333])

In [51]:
np.reshape(a, (4,))

array([ 1.,  2.,  5.,  4.])

In [53]:
np.reshape(a, (4,)), np.ravel(a) # flattening

(array([ 1.,  2.,  5.,  4.]), array([ 1.,  2.,  5.,  4.]))

In [54]:
a.reshape((4, 1))

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 4.]])

In [57]:
a.reshape((-1, 1)) # a[-1] means 'whatever needs to go there'

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 4.]])

In [59]:
np.hstack([a, b])

array([[ 1.,  2.,  4.,  3.],
       [ 5.,  4.,  2.,  1.]])

In [60]:
np.vstack([a, b])

array([[ 1.,  2.],
       [ 5.,  4.],
       [ 4.,  3.],
       [ 2.,  1.]])

In [64]:
v

array([ 0.5,  2. ])

In [70]:
np.vstack([a, b]) + v.reshape([1,2]) # broadcasting, assumes a (2,) vector is seen as a (1,2) vector

array([[ 1.5,  4. ],
       [ 5.5,  6. ],
       [ 4.5,  5. ],
       [ 2.5,  3. ]])

In [72]:
np.hstack([a, b]).shape

(2, 4)

In [75]:
np.hstack([a, b]) + v.reshape([2,1]) # does not work

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [76]:
np.hstack([a, b]) + v.T # transposing a 1-D array achieves nothing

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [78]:
np.hstack([a, b]) + v.reshape((-1, 1)) # reshaping to convert v from a (2,) vector to a (2,1) matrix

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [79]:
np.hstack([a, b]) + v[:, np.newaxis] # equivalently, we can add an axis

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [85]:
np.dstack([a, b, b , b]) # 

array([[[ 1.,  4.,  4.],
        [ 2.,  3.,  3.]],

       [[ 5.,  2.,  2.],
        [ 4.,  1.,  1.]]])

In [89]:
np.dstack([a, b, b, b]).shape

(2, 2, 4)

In [90]:
r = np.random.random_integers(0, 9, size=(3, 4))

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 9 + 1) instead
  if __name__ == '__main__':


In [91]:
r

array([[0, 2, 3, 5],
       [3, 4, 5, 8],
       [7, 2, 5, 3]])

In [93]:
r[0], r[1], r[:,0] # retrieve rows and columns

(array([0, 2, 3, 5]), array([3, 4, 5, 8]), array([0, 3, 7]))

In [94]:
r[0:2]

array([[0, 2, 3, 5],
       [3, 4, 5, 8]])

In [95]:
r[1][2] # regular python

5

In [96]:
r[1, 2] # numpy

5

In [97]:
r[:, 1:3]

array([[2, 3],
       [4, 5],
       [2, 5]])

In [98]:
r > 5

array([[False, False, False, False],
       [False, False, False,  True],
       [ True, False, False, False]], dtype=bool)

In [99]:
r[r > 5]

array([8, 7])

In [100]:
r[r > 5] = 999

In [101]:
r

array([[  0,   2,   3,   5],
       [  3,   4,   5, 999],
       [999,   2,   5,   3]])